import './globals.css'
import './player-fixes.css'
import './chat-improvements.css'
import './chat-hide-code.css'
import './gameplay-v2.css'
import './about-link.css'
import './role-exit.css'
import './game-modals.css'
import './playful-dark.css'
import './mobile-keyboard.css'
import './chat-header-timer.css'
import './redesign-2026.css'
import './skip-phase.css'
import './chat-bottom-boundary.css'
import './action-lock.css'
import './chat-title-timer.css'
import './phase-transitions.css'
import './phase-sound.css'
import MobileKeyboardViewport from '../components/MobileKeyboardViewport'
import ChatAutoScroll from '../components/ChatAutoScroll'
import SkipPhaseVote from '../components/SkipPhaseVote'
import PlayAgainControl from '../components/PlayAgainControl'
import PhaseTransitions from '../components/PhaseTransitions'
export const metadata={title:'Mafia by Ibro — Мафия онлайн',description:'Mafia by Ibro — атмосферная онлайн-мафия с событиями и автоматическим ведущим'}
const inviteGuard="try{if(new URLSearchParams(location.search).has('room'))localStorage.removeItem('mafia-room')}catch(e){}"
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="ru"><body><script dangerouslySetInnerHTML={{__html:inviteGuard}}/><MobileKeyboardViewport/><ChatAutoScroll/><SkipPhaseVote/><PlayAgainControl/><PhaseTransitions/>{children}</body></html>}