'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'
import {HomeView,LobbyView,GameView} from '../components/Views'

export default function Home(){
 const [tab,setTab]=useState<'create'|'join'>('create'),[name,setName]=useState(''),[code,setCode]=useState(''),[roomId,setRoomId]=useState<string|null>(null),[uid,setUid]=useState(''),[room,setRoom]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[role,setRole]=useState<any>(null),[mission,setMission]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState(''),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[chat,setChat]=useState<'general'|'mafia'|'dead'>('general')
 const me=players.find(p=>p.user_id===uid),host=room?.host_id===uid,alive=me?.status==='alive',mafia=role?.team==='mafia',event=events.find(e=>e.day===room?.current_day)
 const filtered=useMemo(()=>messages.filter(m=>m.channel==='system'||m.channel===chat),[messages,chat])
 async function auth(){let s=(await supabase.auth.getSession()).data.session;if(!s){const r=await supabase.auth.signInAnonymously();if(r.error)throw r.error;s=r.data.session}if(!s)throw Error('Нет гостевой сессии');setUid(s.user.id);return s.user.id}
 async function enter(){if(name.trim().length<2)return setError('Введите имя минимум из 2 символов');setBusy(true);setError('');try{await auth();const fn=tab==='create'?'create_game_room':'join_game_room';const args=tab==='create'?{p_nickname:name.trim(),p_room_name:'Тёмный город'}:{p_code:code.trim().toUpperCase(),p_nickname:name.trim()};const r=await supabase.rpc(fn,args);if(r.error)throw r.error;setRoomId(r.data)}catch(e:any){setError(e.message.replaceAll('_',' '))}finally{setBusy(false)}}
 async function load(){if(!roomId||!uid)return;setLoading(true);const [r,p,ro,m,ev,mi]=await Promise.all([supabase.from('rooms').select('*').eq('id',roomId).single(),supabase.from('room_players').select('*').eq('room_id',roomId).order('joined_at'),supabase.from('player_roles').select('*').eq('room_id',roomId).eq('user_id',uid).maybeSingle(),supabase.from('messages').select('*').eq('room_id',roomId).order('created_at'),supabase.from('game_events').select('*').eq('room_id',roomId).order('id',{ascending:false}),supabase.from('player_missions').select('*').eq('room_id',roomId).eq('user_id',uid).maybeSingle()]);if(r.error||p.error)setError(r.error?.message||p.error?.message||'Ошибка загрузки');else{setRoom(r.data);setPlayers(p.data||[])}setRole(ro.data);setMessages(m.data||[]);setEvents(ev.data||[]);setMission(mi.data);setLoading(false)}
 useEffect(()=>{auth().catch(()=>{});const q=new URLSearchParams(location.search).get('room');if(q){setTab('join');setCode(q.toUpperCase())}const saved=localStorage.getItem('mafia-room');if(saved)setRoomId(saved)},[])
 useEffect(()=>{if(!roomId||!uid)return;localStorage.setItem('mafia-room',roomId);load();const c=supabase.channel('r-'+roomId);['rooms','room_players','messages','game_events'].forEach(t=>c.on('postgres_changes',{event:'*',schema:'public',table:t,filter:t==='rooms'?`id=eq.${roomId}`:`room_id=eq.${roomId}`},load));c.subscribe();return()=>{supabase.removeChannel(c)}},[roomId,uid])
 useEffect(()=>{setChat(!alive?'dead':room?.status==='night'&&mafia?'mafia':'general')},[alive,mafia,room?.status])
 useEffect(()=>{const t=setInterval(()=>setSeconds(room?.phase_ends_at?Math.max(0,Math.ceil((new Date(room.phase_ends_at).getTime()-Date.now())/1000)):0),1000);return()=>clearInterval(t)},[room?.phase_ends_at])
 async function rpc(fn:string,args:any){setError('');const r=await supabase.rpc(fn,args);if(r.error)setError(r.error.message);await load()}
 const actions={ready:()=>rpc('set_player_ready',{p_room:roomId,p_ready:!me?.is_ready}),start:()=>rpc('start_game',{p_room:roomId}),advance:()=>rpc('advance_game',{p_room:roomId}),act:()=>selected&&rpc(room?.status==='voting'?'cast_vote':'submit_night_action',{p_room:roomId,p_target:selected}),send:async()=>{if(!text.trim())return;await rpc('send_game_message',{p_room:roomId,p_channel:chat,p_body:text.trim()});setText('')},leave:()=>{localStorage.removeItem('mafia-room');setRoomId(null);setRoom(null)}}
 if(!roomId)return <HomeView {...{tab,setTab,name,setName,code,setCode,busy,error,enter}}/>
 if(loading&&!room)return <main className="app"><div className="panel lobbyLoading"><div className="spinner"/><h2>Загружаем игру</h2></div></main>
 if(!room)return <main className="app"><div className="notice">{error||'Комната недоступна'}</div><button className="primary" onClick={actions.leave}>На главную</button></main>
 if(room.status==='waiting')return <LobbyView {...{room,players,me,host,error,actions}}/>
 return <GameView {...{room,players,role,mission,event,messages:filtered,uid,alive,mafia,chat,setChat,text,setText,error,selected,setSelected,seconds,actions}}/>
}
