'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'
import {HomeView,LobbyView,GameView} from '../components/Views'

const errors:any={NOT_NIGHT:'Сейчас не ночь',NOT_VOTING:'Сейчас нельзя голосовать',DEAD_PLAYER:'Вы уже выбыли',INVALID_TARGET:'Эта цель недоступна',NO_ACTION:'У вашей роли нет ночного действия',CANNOT_TARGET_SELF:'Эта роль не может выбрать себя',CANNOT_TARGET_MAFIA:'Нельзя выбрать участника мафии',DOCTOR_REPEAT_TARGET:'Доктор не может лечить одну цель две ночи подряд',CANNOT_VOTE_SELF:'Нельзя голосовать за себя',GENERAL_CHAT_CLOSED:'Общий чат сейчас закрыт',MAFIA_CHAT_CLOSED:'Чат мафии доступен только ночью',YOU_ARE_BLACKMAILED:'Сегодня вы не можете писать из-за шантажа',TOO_EARLY:'Таймер фазы ещё не закончился'}
const humanError=(value?:string)=>errors[value||'']||errors[value?.split(':').pop()||'']||value?.replaceAll('_',' ')||'Произошла ошибка'

export default function Home(){
 const [tab,setTab]=useState<'create'|'join'>('create'),[name,setName]=useState(''),[code,setCode]=useState(''),[roomId,setRoomId]=useState<string|null>(null),[uid,setUid]=useState(''),[room,setRoom]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[role,setRole]=useState<any>(null),[mission,setMission]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState(''),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[chat,setChat]=useState<'general'|'mafia'|'dead'>('general'),[screen,setScreen]=useState<'game'|'chat'|'players'|'role'>('game'),[actionBusy,setActionBusy]=useState(false),[actionMessage,setActionMessage]=useState('')
 const me=players.find(p=>p.user_id===uid),host=room?.host_id===uid,alive=me?.status==='alive',mafia=role?.team==='mafia',event=events.find(e=>e.day===room?.current_day)
 const filtered=useMemo(()=>messages.filter(m=>m.channel==='system'||m.channel===chat),[messages,chat])
 async function auth(){let s=(await supabase.auth.getSession()).data.session;if(!s){const r=await supabase.auth.signInAnonymously();if(r.error)throw r.error;s=r.data.session}if(!s)throw Error('Нет гостевой сессии');setUid(s.user.id);return s.user.id}
 async function enter(){if(name.trim().length<2)return setError('Введите имя минимум из 2 символов');setBusy(true);setError('');try{await auth();const fn=tab==='create'?'create_game_room':'join_game_room';const args=tab==='create'?{p_nickname:name.trim(),p_room_name:'Тёмный город'}:{p_code:code.trim().toUpperCase(),p_nickname:name.trim()};const r=await supabase.rpc(fn,args);if(r.error)throw r.error;setRoomId(r.data)}catch(e:any){setError(humanError(e.message))}finally{setBusy(false)}}
 async function load(){if(!roomId||!uid)return;setLoading(true);const [r,p,ro,m,ev,mi]=await Promise.all([supabase.from('rooms').select('*').eq('id',roomId).single(),supabase.from('room_players').select('*').eq('room_id',roomId).order('joined_at'),supabase.from('player_roles').select('*').eq('room_id',roomId).eq('user_id',uid).maybeSingle(),supabase.from('messages').select('*').eq('room_id',roomId).order('created_at'),supabase.from('game_events').select('*').eq('room_id',roomId).order('id',{ascending:false}),supabase.from('player_missions').select('*').eq('room_id',roomId).eq('user_id',uid).maybeSingle()]);if(r.error||p.error)setError(humanError(r.error?.message||p.error?.message));else{setRoom(r.data);setPlayers(p.data||[])}setRole(ro.data);setMessages(m.data||[]);setEvents(ev.data||[]);setMission(mi.data);setLoading(false)}
 useEffect(()=>{auth().catch(()=>{});const q=new URLSearchParams(location.search).get('room');if(q){setTab('join');setCode(q.toUpperCase())}const saved=localStorage.getItem('mafia-room');if(saved)setRoomId(saved)},[])
 useEffect(()=>{if(!roomId||!uid)return;localStorage.setItem('mafia-room',roomId);load();const c=supabase.channel('r-'+roomId);['rooms','room_players','messages','game_events','player_roles','player_missions'].forEach(t=>c.on('postgres_changes',{event:'*',schema:'public',table:t,filter:t==='rooms'?`id=eq.${roomId}`:`room_id=eq.${roomId}`},load));c.subscribe();return()=>{supabase.removeChannel(c)}},[roomId,uid])
 useEffect(()=>{setChat(!alive?'dead':room?.status==='night'&&mafia?'mafia':'general')},[alive,mafia,room?.status])
 useEffect(()=>{setSelected('');setActionMessage('')},[room?.status,room?.current_day])
 useEffect(()=>{const update=()=>setSeconds(room?.phase_ends_at?Math.max(0,Math.ceil((new Date(room.phase_ends_at).getTime()-Date.now())/1000)):0);update();const t=setInterval(update,1000);return()=>clearInterval(t)},[room?.phase_ends_at])
 useEffect(()=>{if(!roomId||!room?.phase_ends_at||['waiting','finished'].includes(room.status)||seconds>0)return;const endsAt=new Date(room.phase_ends_at).getTime();if(Date.now()<endsAt)return;const key=`${roomId}:${room.status}:${room.current_day}:${room.phase_ends_at}`;if(sessionStorage.getItem('auto-phase')===key)return;sessionStorage.setItem('auto-phase',key);supabase.rpc('advance_game',{p_room:roomId}).then(()=>load())},[seconds,roomId,room?.status,room?.current_day,room?.phase_ends_at])
 async function rpc(fn:string,args:any){setError('');const r=await supabase.rpc(fn,args);if(r.error){setError(humanError(r.error.message));return false}await load();return true}
 async function submitAction(){if(!selected||!roomId||actionBusy)return;setActionBusy(true);setError('');setActionMessage('');const voting=room?.status==='voting';const ok=await rpc(voting?'cast_vote':'submit_night_action',{p_room:roomId,p_target:selected});if(ok){const target=players.find(p=>p.user_id===selected)?.nickname||'игрок';setActionMessage(voting?`Голос за ${target} принят`:`Действие на ${target} подтверждено`)}setActionBusy(false)}
 const actions={ready:()=>rpc('set_player_ready',{p_room:roomId,p_ready:!me?.is_ready}),start:()=>rpc('start_game',{p_room:roomId}),act:submitAction,send:async()=>{if(!text.trim())return;const ok=await rpc('send_game_message',{p_room:roomId,p_channel:chat,p_body:text.trim()});if(ok)setText('')},leave:()=>{localStorage.removeItem('mafia-room');setRoomId(null);setRoom(null);setScreen('game')}}
 if(!roomId)return <HomeView {...{tab,setTab,name,setName,code,setCode,busy,error,enter}}/>
 if(loading&&!room)return <main className="app"><div className="panel lobbyLoading"><div className="spinner"/><h2>Загружаем игру</h2></div></main>
 if(!room)return <main className="app"><div className="notice">{error||'Комната недоступна'}</div><button className="primary" onClick={actions.leave}>На главную</button></main>
 if(room.status==='waiting')return <LobbyView {...{room,players,me,host,error,actions}}/>
 return <GameView {...{room,players,me,role,mission,event,messages:filtered,uid,alive,mafia,chat,setChat,text,setText,error,selected,setSelected,seconds,actions,screen,setScreen,actionBusy,actionMessage}}/>
}