'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'
import {HomeView,LobbyView,GameView} from '../components/Views'

const errors:any={NOT_NIGHT:'Сейчас не ночь',NOT_VOTING:'Сейчас нельзя голосовать',DEAD_PLAYER:'Вы уже выбыли',INVALID_TARGET:'Эта цель недоступна',NO_ACTION:'У вашей роли нет ночного действия',CANNOT_TARGET_SELF:'Эта роль не может выбрать себя',CANNOT_TARGET_MAFIA:'Нельзя выбрать участника мафии',DOCTOR_REPEAT_TARGET:'Доктор не может лечить одну цель две ночи подряд',CANNOT_VOTE_SELF:'Нельзя голосовать за себя',GENERAL_CHAT_CLOSED:'Общий чат сейчас закрыт',MAFIA_CHAT_CLOSED:'Чат мафии доступен только ночью',YOU_ARE_BLACKMAILED:'Сегодня вы не можете писать из-за шантажа',TOO_EARLY:'Таймер фазы ещё не закончился'}
const humanError=(value?:string)=>errors[value||'']||errors[value?.split(':').pop()||'']||value?.replaceAll('_',' ')||'Произошла ошибка'
const GuideLink=()=> <Link className="aboutFloating" href="/about" aria-label="Открыть правила игры"><b>?</b><span>Об игре</span></Link>

function winnerName(winner?:string){if(winner==='city'||winner==='town')return 'Город';if(winner==='mafia')return 'Мафия';if(winner==='jester')return 'Шут';if(winner==='maniac')return 'Маньяк';return 'Партия завершена'}
function winnerIcon(winner?:string){if(winner==='city'||winner==='town')return '🏙️';if(winner==='mafia')return '🔪';if(winner==='jester')return '🃏';if(winner==='maniac')return '🪓';return '🎭'}

export default function Home(){
 const [tab,setTab]=useState<'create'|'join'>('create'),[name,setName]=useState(''),[code,setCode]=useState(''),[roomId,setRoomId]=useState<string|null>(null),[uid,setUid]=useState(''),[room,setRoom]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[role,setRole]=useState<any>(null),[mission,setMission]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState(''),[seconds,setSeconds]=useState(0),[serverOffset,setServerOffset]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[chat,setChat]=useState<'general'|'mafia'|'dead'>('general'),[screen,setScreen]=useState<'game'|'chat'|'players'|'role'>('game'),[actionBusy,setActionBusy]=useState(false),[actionMessage,setActionMessage]=useState(''),[lastWordText,setLastWordText]=useState(''),[lastWordBusy,setLastWordBusy]=useState(false),[lastWordHidden,setLastWordHidden]=useState(false),[resultHidden,setResultHidden]=useState(false)
 const me=players.find(p=>p.user_id===uid),host=room?.host_id===uid,alive=me?.status==='alive',mafia=role?.team==='mafia',event=events.find(e=>e.day===room?.current_day)
 const filtered=useMemo(()=>messages.filter(m=>m.channel==='system'||m.channel===chat),[messages,chat])
 const personalWin=Boolean(role?.metadata?.personal_win)
 const won=personalWin||(room?.winner==='mafia'&&role?.team==='mafia')||(['city','town'].includes(room?.winner)&&role?.team==='town')||(room?.winner==='jester'&&role?.role_key==='jester')||(room?.winner==='maniac'&&role?.role_key==='maniac')
 async function auth(){let s=(await supabase.auth.getSession()).data.session;if(!s){const r=await supabase.auth.signInAnonymously();if(r.error)throw r.error;s=r.data.session}if(!s)throw Error('Нет гостевой сессии');setUid(s.user.id);return s.user.id}
 async function enter(){if(name.trim().length<2)return setError('Введите имя минимум из 2 символов');setBusy(true);setError('');try{await auth();const fn=tab==='create'?'create_game_room':'join_game_room';const args=tab==='create'?{p_nickname:name.trim(),p_room_name:'Тёмный город'}:{p_code:code.trim().toUpperCase(),p_nickname:name.trim()};const r=await supabase.rpc(fn,args);if(r.error)throw r.error;setRoomId(r.data)}catch(e:any){setError(humanError(e.message))}finally{setBusy(false)}}
 async function load(){if(!roomId||!uid)return;if(!room)setLoading(true);const [r,p,ro,m,ev,mi,st]=await Promise.all([supabase.from('rooms').select('*').eq('id',roomId).single(),supabase.from('room_players').select('*').eq('room_id',roomId).order('joined_at'),supabase.from('player_roles').select('*').eq('room_id',roomId).eq('user_id',uid).maybeSingle(),supabase.from('messages').select('*').eq('room_id',roomId).order('created_at'),supabase.from('game_events').select('*').eq('room_id',roomId).order('id',{ascending:false}),supabase.from('player_missions').select('*').eq('room_id',roomId).eq('user_id',uid).maybeSingle(),supabase.rpc('get_server_time')]);if(r.error||p.error)setError(humanError(r.error?.message||p.error?.message));else{setRoom(r.data);setPlayers(p.data||[])}if(st.data)setServerOffset(new Date(st.data).getTime()-Date.now());setRole(ro.data);setMessages(m.data||[]);setEvents(ev.data||[]);setMission(mi.data);setLoading(false)}
 useEffect(()=>{auth().catch(()=>{});const q=new URLSearchParams(location.search).get('room');if(q){setTab('join');setCode(q.toUpperCase())}const saved=localStorage.getItem('mafia-room');if(saved)setRoomId(saved)},[])
 useEffect(()=>{if(!roomId||!uid)return;localStorage.setItem('mafia-room',roomId);load();const refresh=()=>load();const c=supabase.channel(`game-${roomId}-${uid}`);['rooms','room_players','messages','game_events','player_roles','player_missions','votes','night_actions'].forEach(t=>c.on('postgres_changes',{event:'*',schema:'public',table:t,filter:t==='rooms'?`id=eq.${roomId}`:`room_id=eq.${roomId}`},refresh));c.subscribe(s=>{if(s==='SUBSCRIBED')refresh()});const poll=setInterval(refresh,2000);const resume=()=>document.visibilityState==='visible'&&refresh();window.addEventListener('focus',refresh);window.addEventListener('online',refresh);document.addEventListener('visibilitychange',resume);return()=>{clearInterval(poll);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);document.removeEventListener('visibilitychange',resume);supabase.removeChannel(c)}},[roomId,uid])
 useEffect(()=>{if(room?.status==='role_reveal')setScreen('role')},[room?.status])
 useEffect(()=>{setChat(!alive?'dead':room?.status==='night'&&mafia?'mafia':'general')},[alive,mafia,room?.status])
 useEffect(()=>{setSelected('');setActionMessage('')},[room?.status,room?.current_day])
 useEffect(()=>{if(!me?.last_word_available){setLastWordHidden(false);setLastWordText('')}},[me?.last_word_available])
 useEffect(()=>{setResultHidden(false)},[roomId,room?.winner])
 useEffect(()=>{const update=()=>setSeconds(room?.phase_ends_at?Math.max(0,Math.ceil((new Date(room.phase_ends_at).getTime()-(Date.now()+serverOffset))/1000)):0);update();const t=setInterval(update,250);return()=>clearInterval(t)},[room?.phase_ends_at,serverOffset])
 useEffect(()=>{if(!roomId||!room?.phase_ends_at||['waiting','finished'].includes(room.status)||seconds>0)return;const endsAt=new Date(room.phase_ends_at).getTime();if(Date.now()+serverOffset<endsAt)return;const key=`${roomId}:${room.status}:${room.current_day}:${room.phase_ends_at}`;if(sessionStorage.getItem('auto-phase')===key)return;sessionStorage.setItem('auto-phase',key);supabase.rpc('advance_game',{p_room:roomId}).then(()=>load())},[seconds,roomId,room?.status,room?.current_day,room?.phase_ends_at,serverOffset])
 async function rpc(fn:string,args:any){setError('');const r=await supabase.rpc(fn,args);if(r.error){setError(humanError(r.error.message));return false}await load();return true}
 async function submitAction(){if(!selected||!roomId||actionBusy)return;setActionBusy(true);setError('');setActionMessage('');const voting=room?.status==='voting';const ok=await rpc(voting?'cast_vote':'submit_night_action',{p_room:roomId,p_target:selected});if(ok){const target=players.find(p=>p.user_id===selected)?.nickname||'игрок';setActionMessage(voting?`Голос за ${target} принят`:`Действие на ${target} подтверждено`)}setActionBusy(false)}
 async function sendLastWord(){if(!roomId||!lastWordText.trim()||lastWordBusy)return;setLastWordBusy(true);const ok=await rpc('send_game_message',{p_room:roomId,p_channel:'general',p_body:lastWordText.trim()});if(ok){setLastWordText('');setLastWordHidden(true);setChat('dead');setScreen('chat')}setLastWordBusy(false)}
 const actions={ready:()=>rpc('set_player_ready',{p_room:roomId,p_ready:!me?.is_ready}),start:async()=>{const ok=await rpc('start_game',{p_room:roomId});if(ok)setScreen('role')},act:submitAction,send:async()=>{if(!text.trim())return;const ok=await rpc('send_game_message',{p_room:roomId,p_channel:chat,p_body:text.trim()});if(ok)setText('')},leave:()=>{localStorage.removeItem('mafia-room');setRoomId(null);setRoom(null);setScreen('game');setResultHidden(false);setLastWordHidden(false)}}
 if(!roomId)return <><HomeView {...{tab,setTab,name,setName,code,setCode,busy,error,enter}}/><GuideLink/></>
 if(loading&&!room)return <><main className="app"><div className="panel lobbyLoading"><div className="spinner"/><h2>Загружаем игру</h2></div></main><GuideLink/></>
 if(!room)return <><main className="app"><div className="notice">{error||'Комната недоступна'}</div><button className="primary" onClick={actions.leave}>На главную</button></main><GuideLink/></>
 if(room.status==='waiting')return <><LobbyView {...{room,players,me,host,error,actions}}/><GuideLink/></>
 return <><GameView {...{room,players,me,role,mission,event,messages:filtered,uid,alive,mafia,chat,setChat,text,setText,error,selected,setSelected,seconds,actions,screen,setScreen,actionBusy,actionMessage}}/>{screen==='role'&&<button className="roleExitButton" onClick={actions.leave}>Выйти из комнаты</button>}<GuideLink/>
  {me?.last_word_available&&!lastWordHidden&&room.status!=='finished'&&<div className="gameModalBackdrop" role="dialog" aria-modal="true" aria-labelledby="last-word-title"><div className="gameModal dangerModal"><div className="modalSymbol">💀</div><div className="eyebrow">вы покинули игру</div><h2 id="last-word-title">Ваше последнее слово</h2><p>Живые игроки увидят это сообщение в общем чате. Отправить его можно только один раз.</p><textarea autoFocus maxLength={500} rows={4} value={lastWordText} onChange={e=>setLastWordText(e.target.value)} placeholder="Напишите последнее сообщение..."/><div className="modalCounter">{lastWordText.length} / 500</div>{error&&<div className="notice">{error}</div>}<div className="modalActions"><button className="secondary" onClick={()=>{setLastWordHidden(true);setChat('dead');setScreen('chat')}}>Написать позже</button><button className="primary" disabled={!lastWordText.trim()||lastWordBusy} onClick={sendLastWord}>{lastWordBusy?'Отправляем...':'Отправить живым'}</button></div></div></div>}
  {room.status==='finished'&&!resultHidden&&<div className="gameModalBackdrop resultBackdrop" role="dialog" aria-modal="true" aria-labelledby="result-title"><div className={'gameModal resultModal '+(won?'victoryModal':'defeatModal')}><div className="resultGlow"/><div className="modalSymbol">{won?'🏆':'🌑'}</div><div className="eyebrow">партия завершена</div><h1 id="result-title">{won?'Победа':'Поражение'}</h1><div className="winnerSide"><span>{winnerIcon(room.winner)}</span><div><small>Победившая сторона</small><b>{winnerName(room.winner)}</b></div></div><div className="resultDetails"><div><small>Ваша роль</small><b>{role?.role_key||'Неизвестно'}</b></div><div><small>Статус</small><b>{me?.status==='alive'?'Вы выжили':'Вы выбыли'}</b></div></div>{personalWin&&<div className="personalVictory">✓ Ваша персональная цель выполнена</div>}{room.last_result&&<p className="finalResultText">{room.last_result}</p>}<div className="modalActions"><button className="secondary" onClick={()=>{setResultHidden(true);setScreen('game')}}>Посмотреть итоги</button><button className="primary" onClick={actions.leave}>Выйти на главную</button></div></div></div>}
 </>
}