'use client'
import {useEffect,useRef,useState} from 'react'
import {roles,phaseNames,eventIcons,eventEffects} from './data'

export function Header({leave}:{leave?:()=>void}){return <header className="top"><div><div className="brand">Mafia by Ibro</div><small className="muted">Тёмный город</small></div>{leave?<button className="mini" onClick={leave}>Выйти</button>:<div className="badge">● онлайн</div>}</header>}
export function HomeView(p:any){return <main className="app"><Header/><section className="hero"><div className="eyebrow">город не спит</div><h1>Никому<br/>не доверяй.</h1><p>Онлайн-мафия с активными ролями, происшествиями и автоматическим ведущим.</p></section><section className="panel"><div className="tabs"><button className={'tab '+(p.tab==='create'?'active':'')} onClick={()=>p.setTab('create')}>Создать игру</button><button className={'tab '+(p.tab==='join'?'active':'')} onClick={()=>p.setTab('join')}>Войти по коду</button></div><input className="field" placeholder="Ваше имя" value={p.name} onChange={(e:any)=>p.setName(e.target.value)}/>{p.tab==='join'&&<input className="field" placeholder="Код комнаты" value={p.code} onChange={(e:any)=>p.setCode(e.target.value.toUpperCase())}/>}<button className="primary" disabled={p.busy} onClick={p.enter}>{p.busy?'Подключение...':p.tab==='create'?'Создать комнату':'Войти в комнату'}</button>{p.error&&<div className="notice">{p.error}</div>}<div className="features"><div className="feature"><b>🎭 12 ролей</b><span>Способности реально влияют на партию</span></div><div className="feature"><b>⚡ 10 происшествий</b><span>Меняют чат, время, голоса и защиту</span></div><div className="feature"><b>👥 Живая партия</b><span>Все действия синхронизируются в реальном времени</span></div><div className="feature"><b>💬 Удобные чаты</b><span>Общий, мафиозный и посмертный</span></div></div></section></main>}
export function LobbyView({room,players,me,host,error,actions}:any){return <main className="app"><Header leave={actions.leave}/><section className="panel"><div className="roomHeader"><div><small className="muted">{room.name}</small><h2>Лобби</h2></div></div><div className="lobbyInvite"><div className="eyebrow">код комнаты</div><div className="bigCode">{room.code}</div><p>Отправьте код или ссылку друзьям.</p><div className="inviteActions"><button className="secondary" onClick={()=>navigator.clipboard.writeText(room.code)}>Копировать код</button><button className="secondary" onClick={()=>navigator.clipboard.writeText(`${location.origin}?room=${room.code}`)}>Копировать ссылку</button></div></div><div className="waitingRow"><b>Ожидание игроков</b><span>{players.length} / {room.max_players}</span></div><div className="players">{players.map((x:any)=><div className="player" key={x.user_id}><div className="avatar">{x.user_id===room.host_id?'👑':'🎭'}</div><div className="playerName">{x.nickname}</div><div className={x.is_ready?'alive':'dead'}>{x.is_ready?'● готов':'○ не готов'}</div></div>)}</div><div className="stickyActions"><button className="secondary" onClick={actions.ready}>{me?.is_ready?'Отменить готовность':'Я готов'}</button>{host&&<button className="primary" disabled={players.length<4||players.some((x:any)=>!x.is_ready)} onClick={actions.start}>Начать игру</button>}</div>{error&&<div className="notice">{error}</div>}</section></main>}
function BottomNav({screen,setScreen}:{screen:string,setScreen:(s:any)=>void}){const items=[['game','🎮','Игра'],['chat','💬','Чат'],['players','👥','Игроки'],['role','🎭','Роль']];return <nav className="bottomNav">{items.map(([key,icon,label])=><button key={key} onClick={()=>setScreen(key)} className={screen===key?'active':''}><span>{icon}</span><small>{label}</small></button>)}</nav>}
function messageTime(value:string){if(!value)return '';return new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(value))}

export function GameView(p:any){
 const chatEndRef=useRef<HTMLDivElement|null>(null),chatRef=useRef<HTMLDivElement|null>(null),inputRef=useRef<HTMLTextAreaElement|null>(null)
 const [awayFromBottom,setAwayFromBottom]=useState(false)
 const info=roles[p.role?.role_key],nightRole=p.role&&['mafia','don','doctor','detective','bodyguard','journalist','blackmailer','maniac'].includes(p.role.role_key)
 const action=p.room.status==='voting'||(p.room.status==='night'&&nightRole)
 const generalOpen=['role_reveal','morning','discussion','voting'].includes(p.room.status)
 const lastWord=!p.alive&&p.me?.last_word_available
 const chatOpen=p.chat==='dead'||(p.chat==='mafia'&&p.room.status==='night'&&p.mafia)||(p.chat==='general'&&((p.alive&&generalOpen)||lastWord))
 const anonymous=p.event&&(p.event.event_key==='anonymous_day'||(p.event.event_key==='blackout'&&['morning','discussion'].includes(p.room.status)))
 const actionTitles:any={mafia:'Выберите жертву',don:'Выберите жертву и проверьте Комиссара',doctor:'Кого защитить этой ночью?',detective:'Кого проверить?',bodyguard:'Кого прикрыть?',journalist:'Кого сравнить?',blackmailer:'Кого лишить голоса в чате?',maniac:'Кого устранить?'}
 const actionTitle=p.room.status==='voting'?'Выберите, кого исключить':actionTitles[p.role?.role_key]||'Выберите цель'
 const canChoose=(x:any)=>{if(!action||!p.alive||x.status!=='alive')return false;if(p.room.status==='voting')return x.user_id!==p.uid;if(p.role?.role_key==='doctor')return true;return x.user_id!==p.uid}
 const scrollBottom=(smooth=true)=>chatEndRef.current?.scrollIntoView({behavior:smooth?'smooth':'auto',block:'end'})
 useEffect(()=>{if(p.screen==='chat'){setTimeout(()=>scrollBottom(false),50);setAwayFromBottom(false);setTimeout(()=>inputRef.current?.focus(),120)}},[p.screen,p.chat])
 useEffect(()=>{if(p.screen==='chat'&&!awayFromBottom)scrollBottom(true)},[p.messages.length])
 const onChatScroll=()=>{const el=chatRef.current;if(!el)return;setAwayFromBottom(el.scrollHeight-el.scrollTop-el.clientHeight>100)}
 const send=()=>{if(!chatOpen||!p.text.trim())return;p.actions.send();setTimeout(()=>inputRef.current?.focus(),60)}
 return <main className="app gameApp"><Header leave={p.actions.leave}/><section className="gameShell">
  <div className="mobileGameHeader"><div><small className="muted">День {p.room.current_day||0} · {p.room.name}</small><h2>{phaseNames[p.room.status]}</h2></div><button className="code" onClick={()=>navigator.clipboard.writeText(p.room.code)}>{p.room.code}</button></div>
  {p.room.phase_ends_at&&<div className={'timer '+(p.seconds<=5?'timerUrgent':'')}>⏱️ <span>{Math.floor(p.seconds/60)}:{String(p.seconds%60).padStart(2,'0')}</span></div>}
  {p.screen==='game'&&<div className="screenView">{p.room.last_result&&<div className="notice resultNotice">{p.room.last_result}</div>}{p.event&&<div className="eventCard"><div className="eventIcon">{eventIcons[p.event.event_key]||'⚡'}</div><div><div className="eyebrow">активное происшествие</div><h3>{p.event.title}</h3><p>{p.event.description}</p><div className="eventEffect">Эффект: {eventEffects[p.event.event_key]||'Правила дня изменены.'}</div></div></div>}<div className="quickGrid"><button onClick={()=>p.setScreen('role')}><span>🎭</span><b>{info?.[1]||'Роль'}</b><small>{nightRole?'Есть активная способность':'Посмотреть условия роли'}</small></button><button onClick={()=>p.setScreen('players')}><span>👥</span><b>{p.players.filter((x:any)=>x.status==='alive').length} живых</b><small>{action?'Сейчас доступно действие':'Открыть список игроков'}</small></button><button onClick={()=>p.setScreen('chat')}><span>💬</span><b>Открыть чат</b><small>{chatOpen?'Можно писать':'Сейчас только чтение'}</small></button></div>{p.room.status!=='finished'&&<div className="autoPhaseHint">Фаза сменится автоматически после окончания таймера</div>}{p.room.status==='finished'&&<><div className="winner">{p.room.winner==='city'||p.room.winner==='town'?'🏙️ Победил город':p.room.winner==='mafia'?'🔪 Победила мафия':p.room.winner==='jester'?'🃏 Победил Шут':p.room.winner==='maniac'?'🪓 Победил Маньяк':'🎭 Игра завершена'}</div>{p.role?.metadata?.personal_win&&<div className="actionSuccess">✅ Ваша персональная цель выполнена — вы тоже победили</div>}</>}</div>}
  {p.screen==='chat'&&<div className="screenView chatScreen"><div className="chatHeader"><div><h3>{p.chat==='mafia'?'🔪 Чат мафии':p.chat==='dead'?'💀 Чат выбывших':lastWord?'🕯️ Последнее слово':'💬 Общий чат'}</h3><small>{anonymous&&p.chat==='general'?'Имена участников скрыты событием':chatOpen?'Общайтесь и обсуждайте игроков':'Сообщения временно недоступны'}</small></div><span className={'chatStatus chatPhaseTimer '+(p.seconds<=5?'urgent':'')}>⏱️ {p.room.phase_ends_at?`${Math.floor(p.seconds/60)}:${String(p.seconds%60).padStart(2,'0')}`:'—:—'}</span></div><div className="chatTabs">{p.alive&&p.mafia&&<><button className={p.chat==='general'?'active':''} onClick={()=>p.setChat('general')}>🏙️ Город</button><button className={p.chat==='mafia'?'active':''} onClick={()=>p.setChat('mafia')}>🔪 Мафия</button></>}{!p.alive&&<><button className={p.chat==='dead'?'active':''} onClick={()=>p.setChat('dead')}>💀 Выбывшие</button>{p.me?.last_word_available&&<button className={p.chat==='general'?'active':''} onClick={()=>p.setChat('general')}>🕯️ Последнее слово</button>}</>}</div><div className="chatConversation"><div ref={chatRef} onScroll={onChatScroll} className="chat">{p.messages.length===0&&<div className="emptyState"><div>💬</div><b>Начните разговор</b><span>Напишите первое сообщение участникам</span></div>}{p.messages.map((m:any)=>{const author=m.channel==='system'?'🎙️ Ведущий':m.user_id===p.uid?'Вы':anonymous&&m.channel==='general'?'🎭 Аноним':m.nickname;return <div key={m.id} className={'msg '+(m.user_id===p.uid?'me ':'')+(m.channel==='system'?'system':'')}><div className="msgMeta"><strong>{author}</strong><time>{messageTime(m.created_at)}</time></div><div className="msgBody">{m.body}</div></div>})}<div ref={chatEndRef}/></div>{awayFromBottom&&<button className="scrollLatest" onClick={()=>{scrollBottom();setAwayFromBottom(false)}}>↓ Новые сообщения</button>}</div><div className={'composer '+(!chatOpen?'locked':'')}><textarea ref={inputRef} rows={1} maxLength={500} disabled={!chatOpen} value={p.text} onChange={(e:any)=>p.setText(e.target.value.replace(/\n/g,' '))} onKeyDown={(e:any)=>{if(e.key==='Enter'){e.preventDefault();send()}}} placeholder={chatOpen?'Сообщение...':'Чат откроется в следующей фазе'}/><button aria-label="Отправить сообщение" className="send" disabled={!chatOpen||!p.text.trim()} onClick={send}>➤</button></div></div>}
  {p.screen==='players'&&<div className="screenView"><div className="sectionTitle"><div><h3>{action?actionTitle:'👥 Игроки'}</h3><small className="muted">{action?'Выберите доступную цель и подтвердите действие':'Список участников текущей игры'}</small></div><span>{p.players.filter((x:any)=>x.status==='alive').length} живых</span></div><div className="players playerList">{p.players.map((x:any)=>{const enabled=canChoose(x);return <button disabled={!enabled} onClick={()=>p.setSelected(x.user_id)} className={'player playerRow '+(p.selected===x.user_id?'selected ':'')+(x.status!=='alive'?'eliminated ':'')+(!enabled?'unavailable':'')} key={x.user_id}><div className="avatarWrap"><div className="avatar">{x.status==='alive'?'👤':'💀'}</div></div><div className="playerInfo"><div className="playerName">{x.nickname}{x.user_id===p.uid&&<span className="youTag">Вы</span>}</div><div className={x.status==='alive'?'alive':'dead'}>{x.status==='alive'?'В игре':'Выбыл'}{x.vote_weight>1?' · голос ×2':''}</div></div>{p.selected===x.user_id&&<div className="selectedMark">✓</div>}</button>})}</div>{p.actionMessage&&<div className="actionSuccess">✅ {p.actionMessage}</div>}{action&&p.alive&&<div className="stickyActions"><button className="primary confirmAction" disabled={!p.selected||p.actionBusy} onClick={p.actions.act}>{p.actionBusy?'Отправляем...':p.room.status==='voting'?'Подтвердить голос':'Подтвердить действие'}</button></div>}</div>}
  {p.screen==='role'&&<div className="screenView">{info&&<div className="roleCard"><div className="roleIcon">{info[0]}</div><div className="eyebrow">ваша роль</div><h2>{info[1]}</h2><p>{info[2]}</p>{p.role?.metadata?.night_result&&<div className="privateResult">🔐 {p.role.metadata.night_result}</div>}{p.role?.metadata?.vote_shield_day===p.room.current_day&&<div className="privateResult">🛡️ Сегодня вас защищает Чёрный рынок</div>}</div>}<button className="secondary" onClick={()=>p.setScreen('players')}>Перейти к игрокам</button></div>}
  {p.error&&<div className="notice floatingError">{p.error}</div>}
 </section><BottomNav screen={p.screen} setScreen={p.setScreen}/></main>
}