'use client'
import {roles,phaseNames,eventIcons} from './data'

export function Header({leave}:{leave?:()=>void}){return <header className="top"><div><div className="brand">Mafia by Ibro</div><small className="muted">Тёмный город</small></div>{leave?<button className="mini" onClick={leave}>Выйти</button>:<div className="badge">● онлайн</div>}</header>}

export function HomeView(p:any){return <main className="app"><Header/><section className="hero"><div className="eyebrow">город не спит</div><h1>Никому<br/>не доверяй.</h1><p>Онлайн-мафия с 12 ролями, происшествиями, секретными миссиями и автоматическим ведущим.</p></section><section className="panel"><div className="tabs"><button className={'tab '+(p.tab==='create'?'active':'')} onClick={()=>p.setTab('create')}>Создать игру</button><button className={'tab '+(p.tab==='join'?'active':'')} onClick={()=>p.setTab('join')}>Войти по коду</button></div><input className="field" placeholder="Ваше имя" value={p.name} onChange={(e:any)=>p.setName(e.target.value)}/>{p.tab==='join'&&<input className="field" placeholder="Код комнаты" value={p.code} onChange={(e:any)=>p.setCode(e.target.value.toUpperCase())}/>}<button className="primary" disabled={p.busy} onClick={p.enter}>{p.busy?'Подключение...':p.tab==='create'?'Создать комнату':'Войти в комнату'}</button>{p.error&&<div className="notice">{p.error}</div>}<div className="features"><div className="feature"><b>🎭 12 ролей</b><span>Город, мафия и независимые</span></div><div className="feature"><b>⚡ 10 событий</b><span>Каждое утро меняет правила</span></div><div className="feature"><b>🎯 Миссии</b><span>Личная цель в каждой партии</span></div><div className="feature"><b>💬 3 чата</b><span>Город, мафия и выбывшие</span></div></div></section></main>}

export function LobbyView({room,players,me,host,error,actions}:any){return <main className="app"><Header leave={actions.leave}/><section className="panel"><div className="roomHeader"><div><small className="muted">{room.name}</small><h2>Лобби</h2></div></div><div className="lobbyInvite"><div className="eyebrow">код комнаты</div><div className="bigCode">{room.code}</div><p>Отправьте код или ссылку друзьям.</p><div className="inviteActions"><button className="secondary" onClick={()=>navigator.clipboard.writeText(room.code)}>Копировать код</button><button className="secondary" onClick={()=>navigator.clipboard.writeText(`${location.origin}?room=${room.code}`)}>Копировать ссылку</button></div></div><div className="waitingRow"><b>Ожидание игроков</b><span>{players.length} / {room.max_players}</span></div><div className="players">{players.map((x:any)=><div className="player" key={x.user_id}><div className="avatar">{x.user_id===room.host_id?'👑':'🎭'}</div><div className="playerName">{x.nickname}</div><div className={x.is_ready?'alive':'dead'}>{x.is_ready?'● готов':'○ не готов'}</div></div>)}</div><div className="stickyActions"><button className="secondary" onClick={actions.ready}>{me?.is_ready?'Отменить готовность':'Я готов'}</button>{host&&<button className="primary" disabled={players.length<4||players.some((x:any)=>!x.is_ready)} onClick={actions.start}>Начать игру</button>}</div>{error&&<div className="notice">{error}</div>}</section></main>}

function BottomNav({screen,setScreen,unread}:{screen:string,setScreen:(s:any)=>void,unread:number}){const items=[['game','◉','Игра'],['chat','◌','Чат'],['players','♟','Игроки'],['role','♠','Роль']];return <nav className="bottomNav">{items.map(([key,icon,label])=><button key={key} onClick={()=>setScreen(key)} className={screen===key?'active':''}><span>{icon}</span><small>{label}</small>{key==='chat'&&unread>0&&<b>{unread>9?'9+':unread}</b>}</button>)}</nav>}

export function GameView(p:any){
 const info=roles[p.role?.role_key],nightRole=p.role&&['mafia','don','doctor','detective','bodyguard','journalist','blackmailer','maniac'].includes(p.role.role_key),action=p.room.status==='voting'||(p.room.status==='night'&&nightRole)
 const chatOpen=p.chat==='dead'||p.chat==='mafia'||['role_reveal','morning','discussion','voting'].includes(p.room.status)
 const systemCount=p.messages.filter((m:any)=>m.channel==='system').length
 const actionTitle=p.room.status==='voting'?'Выберите, кого исключить':p.role?.team==='mafia'?'Выберите жертву':'Выберите цель способности'
 return <main className="app gameApp"><Header leave={p.actions.leave}/><section className="gameShell">
  <div className="mobileGameHeader"><div><small className="muted">{p.room.name}</small><h2>{phaseNames[p.room.status]}</h2></div><button className="code" onClick={()=>navigator.clipboard.writeText(p.room.code)}>{p.room.code}</button></div>
  {p.seconds>0&&<div className="timer">⏱ {Math.floor(p.seconds/60)}:{String(p.seconds%60).padStart(2,'0')}</div>}

  {p.screen==='game'&&<div className="screenView">
   {p.room.last_result&&<div className="notice resultNotice">{p.room.last_result}</div>}
   {p.event&&<div className="eventCard"><div className="eventIcon">{eventIcons[p.event.event_key]||'⚡'}</div><div><div className="eyebrow">происшествие дня</div><h3>{p.event.title}</h3><p>{p.event.description}</p></div></div>}
   <div className="quickGrid"><button onClick={()=>p.setScreen('role')}><span>♠</span><b>{info?.[1]||'Роль'}</b><small>Посмотреть роль</small></button><button onClick={()=>p.setScreen('players')}><span>♟</span><b>{p.players.filter((x:any)=>x.status==='alive').length} живых</b><small>Игроки и действия</small></button><button onClick={()=>p.setScreen('chat')}><span>◌</span><b>Открыть чат</b><small>{systemCount} сообщений ведущего</small></button></div>
   {p.room.status!=='finished'&&<div className="autoPhaseHint">Фаза сменится автоматически после окончания таймера</div>}
   {p.room.status==='finished'&&<div className="winner">{p.room.winner==='city'||p.room.winner==='town'?'🏙️ Победил город':p.room.winner==='mafia'?'🔪 Победила мафия':p.room.winner==='jester'?'🃏 Победил Шут':p.room.winner==='maniac'?'🪓 Победил Маньяк':'Игра завершена'}</div>}
  </div>}

  {p.screen==='chat'&&<div className="screenView chatScreen"><div className="chatTabs">{p.alive&&<button className={p.chat==='general'?'active':''} onClick={()=>p.setChat('general')}>Город</button>}{p.alive&&p.mafia&&<button className={p.chat==='mafia'?'active':''} onClick={()=>p.setChat('mafia')}>Мафия</button>}{!p.alive&&<button className="active" onClick={()=>p.setChat('dead')}>Выбывшие</button>}</div><div className="chat">{p.messages.length===0&&<div className="emptyState">Пока сообщений нет. Начните обсуждение первым.</div>}{p.messages.map((m:any)=><div key={m.id} className={'msg '+(m.user_id===p.uid?'me ':'')+(m.channel==='system'?'system':'')}><small>{m.channel==='system'?'Ведущий':m.nickname}</small>{m.body}</div>)}</div><div className="composer"><input className="field" disabled={!chatOpen} value={p.text} onChange={(e:any)=>p.setText(e.target.value)} onKeyDown={(e:any)=>e.key==='Enter'&&p.actions.send()} placeholder={chatOpen?'Написать сообщение...':'Чат закрыт'}/><button className="send" disabled={!chatOpen||!p.text.trim()} onClick={p.actions.send}>➤</button></div></div>}

  {p.screen==='players'&&<div className="screenView"><div className="sectionTitle"><div><h3>{action?actionTitle:'Игроки'}</h3><small className="muted">{action?'Нажмите на карточку игрока, затем подтвердите выбор':'Список участников текущей игры'}</small></div><span>{p.players.filter((x:any)=>x.status==='alive').length} живых</span></div><div className="players playerList">{p.players.map((x:any)=>{const disabled=!action||x.status!=='alive'||x.user_id===p.uid;return <button disabled={disabled} onClick={()=>p.setSelected(x.user_id)} className={'player playerRow '+(p.selected===x.user_id?'selected ':'')+(x.status!=='alive'?'eliminated ':'')+(disabled?'unavailable':'')} key={x.user_id}><div className="avatarWrap"><div className="avatar">{x.status==='alive'?'👤':'💀'}</div></div><div className="playerInfo"><div className="playerName">{x.nickname}{x.user_id===p.uid&&<span className="youTag">Вы</span>}</div><div className={x.status==='alive'?'alive':'dead'}>{x.status==='alive'?'В игре':'Выбыл'}{x.vote_weight>1?' · двойной голос':''}</div></div>{p.selected===x.user_id&&<div className="selectedMark">✓</div>}</button>})}</div>{p.actionMessage&&<div className="actionSuccess">✓ {p.actionMessage}</div>}{action&&p.alive&&<div className="stickyActions"><button className="primary confirmAction" disabled={!p.selected||p.actionBusy} onClick={p.actions.act}>{p.actionBusy?'Отправляем...':p.room.status==='voting'?'Подтвердить голос':'Подтвердить действие'}</button></div>}</div>}

  {p.screen==='role'&&<div className="screenView">{info&&<div className="roleCard"><div className="roleIcon">{info[0]}</div><div className="eyebrow">ваша роль</div><h2>{info[1]}</h2><p>{p.room.status==='finished'?'Партия завершена.':info[2]}</p>{p.role?.metadata?.night_result&&<div className="privateResult">🔐 {p.role.metadata.night_result}</div>}</div>}{p.mission&&<div className="missionCard"><div className="missionTop"><span>🎯 Секретная миссия</span><b>+{p.mission.reward} XP</b></div><p>{p.mission.description}</p></div>}<button className="secondary" onClick={()=>p.setScreen('players')}>Перейти к игрокам</button></div>}

  {p.error&&<div className="notice floatingError">{p.error}</div>}
 </section><BottomNav screen={p.screen} setScreen={p.setScreen} unread={0}/></main>
}